
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# 允许网址形式访问
http:
  use_x_forwarded_for: true    
  trusted_proxies:
    - 127.0.0.1

# 认证方式为LDAP
homeassistant:
  auth_providers:
  - type: command_line
    command: /config/ldap-auth.sh
    args: ["/config/ldap-auth.cfg"]
    meta: true
